version: '3.8'

services:
  ai-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-experimentation
    volumes:
      # Mount your local workspace directory to /workspace in the container
      # Change './workspace' to your preferred local directory path
      - ./workspace:/workspace
      # Mount home directory to persist tool configurations and settings
      - ./home:/home/aidev
      # Mount gitconfig
      - ./.gitconfig.template:/home/aidev/.gitconfig:ro
      # Mount SSH keys for git operations (create ~/.ssh in host if needed)
      - ${HOME}/.ssh:/home/aidev/.ssh:ro
    environment:
      # Add any API keys or environment variables here
      # - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      # - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    stdin_open: true
    tty: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "zsh", "-c", "echo healthy"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
